// IL DEFINIT LA LISTE OFFICIELLE DES DONNE AUTORISEE
const TRANSACTION_TYPES = Object.freeze({
  DEPOSIT: "DEPOSIT",
  WITHDRAW: "WITHDRAW",
  TRANSFER: "TRANSFER",
  PAYMENT: "PAYMENT",
  FEE: "FEE",
  CHARGEBACK: "CHARGEBACK",
  HOLD: "HOLD",
  CAPTURE: "CAPTURE",
  REVERSAL: "REVERSAL"
});

module.exports = TRANSACTION_TYPES;
