const TRANSACTION_TYPES = require("./constants/transactionsTypes");
const Transaction = require("./transactionModel");
const crypto = require("crypto");

class Ledger {
  #transactions = [];

  async recordTransaction(
    id,
    type,
    entries,
    reversesTransactionId = null,
    idempotencyKey = null
  ) {
    // IDEMPOTENCY CHECK
    if (idempotencyKey) {
      const existing = idempotencyKey
        ? this.#transactions.find(
            (trx) => trx.idempotencyKey === idempotencyKey
          )
        : null;

      if (existing) return { ...existing };
    }

    // ID AND ENTRIES VALIDATION
    if (!id || typeof id !== "string") {
      throw new Error("invalid Id");
    }

    if (!type || typeof type !== "string") {
      throw new Error("Invalid transaction type");
    }

    if (!Object.values(TRANSACTION_TYPES).includes(type)) {
      throw new Error("Unknow transaction type");
    }

    if (!Array.isArray(entries) || entries.length === 0) {
      throw new Error("Invalid entries");
    }

    // LEDGER MUST BE BALANCE TO ZER0
    let sum = 0;

    for (const entry of entries) {
      if ("entryId" in entry) {
        throw new Error("entryId is generated by ledger");
      }
      if (!entry.accountId || typeof entry.accountId !== "string") {
        throw new Error("Invalid AccountId");
      }

      if (
        typeof entry.amount !== "number" ||
        isNaN(entry.amount) ||
        !isFinite(entry.amount)
      ) {
        throw new Error("Invalid Amount");
      }

      sum += entry.amount;
    }

    // ANTI CORRUPTION WALL , we enforce rules here
    if (sum !== 0) {
      throw new Error("Sum must be balance to Zero");
    }

    if (type === TRANSACTION_TYPES.REVERSAL) {
      if (!reversesTransactionId) {
        throw new Error("Reversal must reference an original transaction");
      }
      const alreadyReversed = this.#transactions.some(
        (trx) => trx.reversesTransactionId === reversesTransactionId
      );

      if (alreadyReversed) {
        throw new Error("Transaction already reversed");
      }
    }

    // PREVENTING DUPLICATE TRANSACTION
    const existingTransaction = this.#transactions.some((trx) => trx.id === id);

    if (existingTransaction) throw new Error("Transaction already exist");

    const freezeEntries = Object.freeze(
      entries.map((entry) =>
        Object.freeze({
          entryId: crypto.randomUUID(),
          ...entry
        })
      )
    );

    // STORE TRANSACTION;
    const transaction = Object.freeze({
      id,
      type,
      reversesTransactionId,
      idempotencyKey,
      entries: freezeEntries,
      timestamp: Date.now()
    });

    this.#transactions.push(transaction);

    // CECI EST POUR TESTER
    await Transaction.create(transaction);

    return { ...transaction };
  }

  // GET BALANCE
  getBalance(id) {
    // VALIDATION
    if (!id || typeof id !== "string") {
      throw new Error("Invalid ID");
    }

    let balance = 0;

    for (let i = 0; i < this.#transactions.length; i++) {
      const entries = this.#transactions[i].entries;

      for (let j = 0; j < entries.length; j++) {
        if (entries[j].accountId === id) {
          balance += entries[j].amount;
        }
      }
    }
    return balance;
  }

  // GET TRANSACTIONS
  getTransactions() {
    return this.#transactions;
  }

  // REVERSE TRANSACTION
  async reverseTransaction(originalTransactionId, reversalTransactionId) {
    if (type === TRANSACTION_TYPES.REVERSAL) {
      if (!reversesTransactionId) {
        throw new Error("Reversal must reference an original transaction");
      }

      const original = this.#getTransaction(reversesTransactionId);

      if (!original) {
        throw new Error("Transaction not found");
      }

      const alreadyReversed = this.#transactions.some(
        (trx) => trx.reversesTransactionId === reversesTransactionId
      );

      if (alreadyReversed) {
        throw new Error("Transaction already reversed");
      }
    }

    const reversedEntries = original.entries.map((entry) => ({
      accountId: entry.accountId,
      amount: -entry.amount
    }));

    return this.recordTransaction(
      reversalTransactionId,
      TRANSACTION_TYPES.REVERSAL,
      reversedEntries,
      originalTransactionId
    );
  }
  // LOAD FROM MONGODB
  async loadFromDB() {
    const data = await Transaction.find();

    this.#transactions = data.map((trx) => ({
      id: trx.id,
      type: trx.type,
      reversesTransactionId: trx.reversesTransactionId,
      idempotencyKey: trx.idempotencyKey,
      entries: trx.entries,
      timestamp: trx.timestamp
    }));
    console.log(`Loaded ${this.#transactions.length} transactions from DB`);
  }

  #getTransaction(id) {
    return this.#transactions.find((trx) => trx.id === id);
  }
}

module.exports = Ledger;
